[build]
# rustflags = ["-C", "target-cpu=native", "--cfg", "tokio_unstable"]
rustflags = ["-C", "target-cpu=native"]

[target.wasm32-unknown-unknown]
rustflags = ["--cfg", "getrandom_backend=\"wasm_js\""]